name: Events Demo 1
on: 
    pull_request:
        types:
            - opened
        branches:
        - main
        - 'dev-*' # wildcard - example dev-new dev-this-is-new
        - 'feat/**' # wildcard example: feat/new feat/new/button
    workflow_dispatch:
    push:
      branches:
        - main
        - 'dev-*' # wildcard - example dev-new dev-this-is-new
        - 'feat/**' # wildcard example: feat/new feat/new/button
      paths:
        - '.github/wrokflows/*' # meaning, push to main when something has changed with anything in the path .github/wrokflows/*

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Uutput event data
              run: echo "${{ toJSON(github.event) }}"
            - name: Get code
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Test code
              run: npm run build
            - name: Deploy project
              run: echo "Deploying..."
